### ISSUE TITLE
Do you have any plans to support terraform configuration in future ?

### ISSUE THREAD

**Issue by NanditaRao** [dowjones/respawn#2]
@vshah505  @kuberkaul I am working with terraform and have been looking for a similar library like respawn that can be levaraged to build terraform config JSON. Do you have any plans for that ? https://www.terraform.io/docs/configuration/index.html

**Comment by scott2449** [comment]
:+1: I asked @kuberkaul about this just the other day!

**Comment by kuberkaul** [comment]
We don't have any plans for terraform yet but will add it to the backlog and look at it in due course. Thank you for using respawn and your recommendation.
